
# Use a versão do n8n baseada em Debian (com suporte ao apt-get)
FROM n8nio/n8n:1.45.1-debian

USER root

# Instala dependências necessárias para nós como Spreadsheet, HTML Extract, etc.
RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  build-essential \
  libxss1 \
  libappindicator1 \
  libnss3 \
  libatk-bridge2.0-0 \
  libgtk-3-0 \
  fonts-liberation \
  libasound2 \
  libcups2 \
  libdbus-1-3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils \
  libgbm-dev \
  wget \
  curl \
  unzip \
  && apt-get clean

# Volta ao usuário padrão do n8n
USER node
